awk '
/<!-- Contact & Collaboration Section -->/ {
    print "    <!-- Web Projects Section -->"
    print "    <section"
    print "      id=\"projects\""
    print "      class=\"py-24 px-6 border-t border-white/5 bg-white/[0.01]\""
    print "    >"
    print "      <div class=\"max-w-7xl mx-auto\">"
    print "        <div"
    print "          class=\"flex flex-col md:flex-row justify-between items-start md:items-end mb-16 reveal-entry\""
    print "        >"
    print "          <div>"
    print "            <span"
    print "              class=\"font-mono text-xs tracking-widest text-[#f59e0b] uppercase\""
    print "              >07 / WEB PROJECTS</span"
    print "            >"
    print "            <h2"
    print "              class=\"mt-2 font-sans text-3xl font-bold tracking-tight text-white\""
    print "            >"
    print "              Interactive Scientific Tools"
    print "            </h2>"
    print "          </div>"
    print "        </div>"
    print ""
    print "        <div class=\"grid grid-cols-1 md:grid-cols-2 gap-8 reveal-entry\">"
    print "          <!-- Project 1: ODE Solver -->"
    print "          <div"
    print "            class=\"liquid-glass rounded-2xl p-8 flex flex-col justify-between h-full group\""
    print "          >"
    print "            <div>"
    print "              <div class=\"flex items-center justify-between mb-6\">"
    print "                <div class=\"flex flex-wrap gap-1.5\">"
    print "                  <span"
    print "                    class=\"px-2 py-0.5 rounded bg-blue-500/10 border border-blue-500/20 text-[11px] font-mono font-semibold text-blue-400 uppercase\""
    print "                    >Python / SymPy</span"
    print "                  >"
    print "                  <span"
    print "                    class=\"px-2 py-0.5 rounded bg-purple-500/10 border border-purple-500/20 text-[11px] font-mono font-semibold text-purple-400 uppercase\""
    print "                    >Data Visualization</span"
    print "                  >"
    print "                </div>"
    print "              </div>"
    print "              <h4"
    print "                class=\"font-sans text-lg font-bold text-white group-hover:text-[#f59e0b] transition-colors duration-300 leading-snug\""
    print "              >"
    print "                Differential Equation Solver"
    print "              </h4>"
    print "              <p"
    print "                class=\"mt-4 font-serif text-[13px] text-slate-400 leading-relaxed text-left\""
    print "              >"
    print "                Developed a Python application that solves ordinary differential equations (ODEs) symbolically with SymPy and visualizes solutions using Matplotlib. The solver supports both first-order and higher-order ODEs, handles initial conditions, and includes direction field visualization for first-order equations to facilitate mathematical analysis."
    print "              </p>"
    print "            </div>"
    print "            <div class=\"mt-8 flex items-center gap-4\">"
    print "              <a"
    print "                href=\"https://nguynhau.github.io/Differential-equation-solver/\""
    print "                target=\"_blank\""
    print "                class=\"text-slate-300 hover:text-white transition-colors flex items-center gap-1.5 font-sans text-xs bg-white/5 hover:bg-white/10 px-4 py-2 rounded-lg border border-white/10 w-full justify-center\""
    print "                title=\"View Application\""
    print "              >"
    print "                <i"
    print "                  data-lucide=\"external-link\""
    print "                  class=\"h-3.5 w-3.5 text-[#f59e0b]\""
    print "                ></i>"
    print "                Launch Application"
    print "              </a>"
    print "            </div>"
    print "          </div>"
    print ""
    print "          <!-- Project 2: Classification Visualizer -->"
    print "          <div"
    print "            class=\"liquid-glass rounded-2xl p-8 flex flex-col justify-between h-full group\""
    print "          >"
    print "            <div>"
    print "              <div class=\"flex items-center justify-between mb-6\">"
    print "                <div class=\"flex flex-wrap gap-1.5\">"
    print "                  <span"
    print "                    class=\"px-2 py-0.5 rounded bg-emerald-500/10 border border-emerald-500/20 text-[11px] font-mono font-semibold text-emerald-400 uppercase\""
    print "                    >Machine Learning</span"
    print "                  >"
    print "                  <span"
    print "                    class=\"px-2 py-0.5 rounded bg-orange-500/10 border border-orange-500/20 text-[11px] font-mono font-semibold text-orange-400 uppercase\""
    print "                    >Interactive Web</span"
    print "                  >"
    print "                </div>"
    print "              </div>"
    print "              <h4"
    print "                class=\"font-sans text-lg font-bold text-white group-hover:text-[#f59e0b] transition-colors duration-300 leading-snug\""
    print "              >"
    print "                Classification Algorithm Visualizer"
    print "              </h4>"
    print "              <p"
    print "                class=\"mt-4 font-serif text-[13px] text-slate-400 leading-relaxed text-left\""
    print "              >"
    print "                An interactive web application for visualizing and comparing machine learning classification algorithms, including SVM, Logistic Regression, Perceptron, Decision Tree, and KNN. Built with HTML5 Canvas and JavaScript, the application features real-time training visualization, PCA-based dimensionality reduction, dynamic decision boundary rendering, and live performance metrics to provide an intuitive understanding of how classification models learn."
    print "              </p>"
    print "            </div>"
    print "            <div class=\"mt-8 flex items-center gap-4\">"
    print "              <a"
    print "                href=\"https://nguynhau.github.io/Visualizer-classification/\""
    print "                target=\"_blank\""
    print "                class=\"text-slate-300 hover:text-white transition-colors flex items-center gap-1.5 font-sans text-xs bg-white/5 hover:bg-white/10 px-4 py-2 rounded-lg border border-white/10 w-full justify-center\""
    print "                title=\"View Application\""
    print "              >"
    print "                <i"
    print "                  data-lucide=\"external-link\""
    print "                  class=\"h-3.5 w-3.5 text-[#f59e0b]\""
    print "                ></i>"
    print "                Launch Application"
    print "              </a>"
    print "            </div>"
    print "          </div>"
    print "        </div>"
    print "      </div>"
    print "    </section>"
    print ""
}
{ print }
' index.html > temp.html && mv temp.html index.html
