const translations = {
  "(Excellent). Defense of Bachelor Thesis graded with a perfect score:": "(Excellent). Defense of Bachelor Thesis graded with a perfect score:",
  "(translated from Vietnamese)": "(translated from Vietnamese)",
  ", I develop mathematically rigorous optimization methods for machine learning. My research focuses on": ", I develop mathematically rigorous optimization methods for machine learning. My research focuses on",
  "01 / OVERVIEW": "01 / OVERVIEW",
  "02 / EDUCATION": "02 / EDUCATION",
  "03 / PUBLICATIONS & ARTICLES": "03 / PUBLICATIONS & ARTICLES",
  "04 / SKILLS": "04 / SKILLS",
  "05 / MERITS & SCHOLARSHIPS": "05 / MERITS & SCHOLARSHIPS",
  "06 / CERTIFICATES & CREDENTIALS": "06 / CERTIFICATES & CREDENTIALS",
  "06 / COLLABORATION INQUIRIES": "06 / COLLABORATION INQUIRIES",
  "@nguynhau__": "@nguynhau__",
  "About": "About",
  "Academic Encouragement Scholarships": "Academic Encouragement Scholarships",
  "Academic Milestones": "Academic Milestones",
  "Academic Portfolio": "Academic Portfolio",
  "Academic Transcripts": "Academic Transcripts",
  "Academic Writing & Research Standards": "Academic Writing & Research Standards",
  "Accepted (Jul 2025 \u2013 Dec 2025)": "Accepted (Jul 2025 \u2013 Dec 2025)",
  "Achievements": "Achievements",
  "Acknowledge Protocol": "Acknowledge Protocol",
  "Affiliation / University": "Affiliation / University",
  "Applied Mathematics": "Applied Mathematics",
  "Applying statistical modeling, machine learning algorithms, and high-dimensional data analysis to extract actionable insights and optimize predictive performance.": "Applying statistical modeling, machine learning algorithms, and high-dimensional data analysis to extract actionable insights and optimize predictive performance.",
  "Apr 2024": "Apr 2024",
  "As a postgraduate researcher in": "As a postgraduate researcher in",
  "Awarded multiple times throughout undergraduate studies (2022\u20132023; 2024\u20132025) for ranking within the top percentile of the Applied Mathematics department.": "Awarded multiple times throughout undergraduate studies (2022\u20132023; 2024\u20132025) for ranking within the top percentile of the Applied Mathematics department.",
  "Bachelor of Applied Mathematics": "Bachelor of Applied Mathematics",
  "Bachelor's Thesis": "Bachelor's Thesis",
  "C/C++": "C/C++",
  "CO-AUTHOR": "CO-AUTHOR",
  "CSS3": "CSS3",
  "Can Tho University (CTU), Vietnam": "Can Tho University (CTU), Vietnam",
  "Can Tho University, Vietnam": "Can Tho University, Vietnam",
  "Can Tho University-level award recognizing academic excellence, morals, and volunteerism.": "Can Tho University-level award recognizing academic excellence, morals, and volunteerism.",
  "College of Natural Sciences award.": "College of Natural Sciences award.",
  "Completed during the discover study exchange program at Universiti Brunei Darussalam, Brunei, focused on biodiversity preservation and sustainable development.": "Completed during the discover study exchange program at Universiti Brunei Darussalam, Brunei, focused on biodiversity preservation and sustainable development.",
  "Computational & Data Science": "Computational & Data Science",
  "Contact": "Contact",
  "Contributions:": "Contributions:",
  "Convex Analysis": "Convex Analysis",
  "Core Mathematics & Theory": "Core Mathematics & Theory",
  "Data Science": "Data Science",
  "Dec 2025": "Dec 2025",
  "Department Excellence": "Department Excellence",
  "Developed a safe screening framework for robust support vector machines (R-SVM) under feature uncertainty, demonstrating substantial training acceleration and computational savings.": "Developed a safe screening framework for robust support vector machines (R-SVM) under feature uncertainty, demonstrating substantial training acceleration and computational savings.",
  "Development Tools & Vibe Coding": "Development Tools & Vibe Coding",
  "EN": "EN",
  "Email": "Email",
  "Email Address": "Email Address",
  "Established geometric and metric characterizations, particularly for convex-valued mappings, using modern tools from variational analysis and nonsmooth optimization.": "Established geometric and metric characterizations, particularly for convex-valued mappings, using modern tools from variational analysis and nonsmooth optimization.",
  "FACULTY-LEVEL": "FACULTY-LEVEL",
  "FIRST AUTHOR": "FIRST AUTHOR",
  "Focusing on advanced optimization algorithms, variational analysis, and dynamic screening rules under sparse structures.": "Focusing on advanced optimization algorithms, variational analysis, and dynamic screening rules under sparse structures.",
  "Formulating fast dual screening tests, dual gap analyses, and primal-dual algorithms to accelerate sparse regressions (LASSO, Group LASSO).": "Formulating fast dual screening tests, dual gap analyses, and primal-dual algorithms to accelerate sparse regressions (LASSO, Group LASSO).",
  "Full Name": "Full Name",
  "Full scholarship by Can Tho University for the discover study exchange program at Universiti Brunei Darussalam covering flight, tuition, and living stipends.": "Full scholarship by Can Tho University for the discover study exchange program at Universiti Brunei Darussalam covering flight, tuition, and living stipends.",
  "Fully funded discovery study on mathematical modeling of socio-ecological environments, computational models, and international collaboration dynamics.": "Fully funded discovery study on mathematical modeling of socio-ecological environments, computational models, and international collaboration dynamics.",
  "Functional Analysis": "Functional Analysis",
  "Future Ocean Changemakers Youth Forum": "Future Ocean Changemakers Youth Forum",
  "GALOIS CONNECTION, PORTFOLIO": "GALOIS CONNECTION, PORTFOLIO",
  "GPA 3.71 (Outstanding)": "GPA 3.71 (Outstanding)",
  "GRADUATE-LEVEL": "GRADUATE-LEVEL",
  "Gap Safe Screening Rules for Fast Training of Robust Support Vector Machines under Feature Noise": "Gap Safe Screening Rules for Fast Training of Robust Support Vector Machines under Feature Noise",
  "Gap-Safe screening rules": "Gap-Safe screening rules",
  "General inquiry": "General inquiry",
  "Git / GitHub": "Git / GitHub",
  "GitHub": "GitHub",
  "Google Colab": "Google Colab",
  "Graduate Study opportunity": "Graduate Study opportunity",
  "Graduated with an outstanding GPA of": "Graduated with an outstanding GPA of",
  "Granted Can Tho University scientific research funding for the student project investigating configurations of set-valued mappings.": "Granted Can Tho University scientific research funding for the student project investigating configurations of set-valued mappings.",
  "Green Stewardship Certificate": "Green Stewardship Certificate",
  "HTML5": "HTML5",
  "Honors & Funding Awards": "Honors & Funding Awards",
  "INTERNATIONAL": "INTERNATIONAL",
  "If you are looking for research partnerships in Mathematical Optimization, Varitional Analysis, or Machine Learning screening paradigms, feel free to reach out.": "If you are looking for research partnerships in Mathematical Optimization, Varitional Analysis, or Machine Learning screening paradigms, feel free to reach out.",
  "Inquire Collaboration": "Inquire Collaboration",
  "Inquiry Purpose": "Inquiry Purpose",
  "Inquiry Received Successfully": "Inquiry Received Successfully",
  "Instagram": "Instagram",
  "International Scholar": "International Scholar",
  "International delegate representation at the youth forum in Brunei, presenting mathematical modelling of environmental ecology and coastal sustainability.": "International delegate representation at the youth forum in Brunei, presenting mathematical modelling of environmental ecology and coastal sustainability.",
  "Investigates non-convex risk-return selection configurations using Galois connections. Implements stable mathematical pairings to prevent volatility divergence under highly volatile asset conditions.": "Investigates non-convex risk-return selection configurations using Galois connections. Implements stable mathematical pairings to prevent volatility divergence under highly volatile asset conditions.",
  "JavaScript": "JavaScript",
  "Journey": "Journey",
  "Jun 2025": "Jun 2025",
  "LaTeX / Overleaf": "LaTeX / Overleaf",
  "Let's connect on scientific optimization": "Let's connect on scientific optimization",
  "LinkedIn": "LinkedIn",
  "MAI LAB": "MAI LAB",
  "MATLAB": "MATLAB",
  "Machine Learning": "Machine Learning",
  "Machine Learning Foundations": "Machine Learning Foundations",
  "Machine Learning: Foundations & Applications": "Machine Learning: Foundations & Applications",
  "Markdown": "Markdown",
  "Master of Applied Mathematics": "Master of Applied Mathematics",
  "Master's student in Applied Mathematics and research trainee with a focus on Data Science at at the College of Natural Sciences, Can Tho University.": "Master's student in Applied Mathematics and research trainee with a focus on Data Science at at the College of Natural Sciences, Can Tho University.",
  "Mathematical & Analytical Toolkit": "Mathematical & Analytical Toolkit",
  "Mathematical Optimization": "Mathematical Optimization",
  "May 2026 \u2013 Present": "May 2026 \u2013 Present",
  "Methodology, Software, Formal Analysis, Investigation, Visualization, Writing \u2013 Original Draft, Writing \u2013 Review & Editing.": "Methodology, Software, Formal Analysis, Investigation, Visualization, Writing \u2013 Original Draft, Writing \u2013 Review & Editing.",
  "Nguyen Tan Hau": "Nguyen Tan Hau",
  "Nguyen Tan Hau | Academic Portfolio - Applied Mathematics & ML": "Nguyen Tan Hau | Academic Portfolio - Applied Mathematics & ML",
  "ORCID: 0009-0006-1357-8882": "ORCID: 0009-0006-1357-8882",
  "Optimization": "Optimization",
  "Optimization Theory": "Optimization Theory",
  "Organized by VIASM & HCMUT \u2013 VNU. Advanced theory on quantum computational logic.": "Organized by VIASM & HCMUT \u2013 VNU. Advanced theory on quantum computational logic.",
  "PDF": "PDF",
  "Phone": "Phone",
  "Portrait (anh2.jpg)": "Portrait (anh2.jpg)",
  "Power BI": "Power BI",
  "Professional Licenses & Certifications": "Professional Licenses & Certifications",
  "Proposed and investigated new regularity and transversality properties for collections of set-valued mappings, extending corresponding concepts for collections of sets.": "Proposed and investigated new regularity and transversality properties for collections of set-valued mappings, extending corresponding concepts for collections of sets.",
  "Python": "Python",
  "R Language": "R Language",
  "RESEARCHER": "RESEARCHER",
  "Regularity of Collections of Set-Valued Mappings": "Regularity of Collections of Set-Valued Mappings",
  "Research": "Research",
  "Research Collaboration": "Research Collaboration",
  "Research Funding": "Research Funding",
  "ResearchGate": "ResearchGate",
  "ResearchGate Profile": "ResearchGate Profile",
  "Rigorous foundations in mathematical learning, optimization proofs, and algorithmic limits.": "Rigorous foundations in mathematical learning, optimization proofs, and algorithmic limits.",
  "SPECIALIZED": "SPECIALIZED",
  "SPSS": "SPSS",
  "SQL": "SQL",
  "SVM, SCREENING, OPTIMIZATION": "SVM, SCREENING, OPTIMIZATION",
  "Scientific Narrative & Research Mission": "Scientific Narrative & Research Mission",
  "Scientific Proposal / Message": "Scientific Proposal / Message",
  "Scientific Research Portfolio": "Scientific Research Portfolio",
  "Send a direct message": "Send a direct message",
  "Sep 2022 \u2013 Feb 2026": "Sep 2022 \u2013 Feb 2026",
  "Skills": "Skills",
  "Solving Risk-Return Tradeoff Model with Galois Connection": "Solving Risk-Return Tradeoff Model with Galois Connection",
  "Speaker request": "Speaker request",
  "Statistical Analysis": "Statistical Analysis",
  "Strengthening support vector machines, neural network convergence proofs, and generalization bounds using analytical metrics.": "Strengthening support vector machines, neural network convergence proofs, and generalization bounds using analytical metrics.",
  "Student Exchange Program": "Student Exchange Program",
  "Student Scientific Research Project (University-level)": "Student Scientific Research Project (University-level)",
  "Study Exchange Full Funding Grant": "Study Exchange Full Funding Grant",
  "Submit Inquiry Protocol": "Submit Inquiry Protocol",
  "TAN-HAU NGUYEN": "TAN-HAU NGUYEN",
  "Thank you for reaching out! Your research request/proposal has been successfully transmitted. Nguyen Tan Hau will review the scientific scope and respond shortly.": "Thank you for reaching out! Your research request/proposal has been successfully transmitted. Nguyen Tan Hau will review the scientific scope and respond shortly.",
  "Thesis Grade: 9.7/10.0": "Thesis Grade: 9.7/10.0",
  "Typst": "Typst",
  "UNIVERSITY-LEVEL": "UNIVERSITY-LEVEL",
  "Under Review (2025)": "Under Review (2025)",
  "Under Review (2026)": "Under Review (2026)",
  "Universiti Brunei Darussalam": "Universiti Brunei Darussalam",
  "University Research Grant": "University Research Grant",
  "VARIATIONAL ANALYSIS": "VARIATIONAL ANALYSIS",
  "VI": "VI",
  "VS Code": "VS Code",
  "Vibe Coding": "Vibe Coding",
  "View Research Papers": "View Research Papers",
  "View Thesis": "View Thesis",
  "Winter School on Quantum Computation": "Winter School on Quantum Computation",
  "Year 2025": "Year 2025",
  "and": "and",
  "for high-dimensional optimization, enabling faster and more scalable algorithms for sparse regression, signal recovery, and related optimization problems.": "for high-dimensional optimization, enabling faster and more scalable algorithms for sparse regression, signal recovery, and related optimization problems.",
  "github.com/NguynHau": "github.com/NguynHau",
  "linkedin.com/in/tan-hau-nguyen-bba3943b7": "linkedin.com/in/tan-hau-nguyen-bba3943b7",
  "nthau.work@gmail.com": "nthau.work@gmail.com",
  "\u00a9 2026 Nguyen Tan Hau. All rights reserved.": "\u00a9 2026 Nguyen Tan Hau. All rights reserved.",
  "\u201cStudent with 5 Good Criteria\u201d": "\u201cStudent with 5 Good Criteria\u201d",
};
